class Config(object):
    BLOGGING_SITENAME = 'Patron'
    BLOGGING_SITEURL = 'https://github.com'
    BLOGGING_BRANDURL = None
    BLOGGING_TWITTER_USERNAME = '@twitter'
    BLOGGING_DISQUS_SITENAME = None
    BLOGGING_GOOGLE_ANALYTICS = None
    BLOGGING_PERMISSIONS = True
    BLOGGING_PERMISSIONNAME = 'admin'
    BLOGGING_PLUGINS = None
    BLOGGING_ALLOW_FILE_UPLOAD = True
