"""empty message

Revision ID: 14de905dee13
Revises: be7c190835cc
Create Date: 2018-12-26 14:37:52.538066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14de905dee13'
down_revision = 'be7c190835cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btc_pay_client_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('btc_pay_client_store')
    # ### end Alembic commands ###
