"""empty message

Revision ID: 33cbe65e05db
Revises: d3d693b8dd81
Create Date: 2019-01-07 23:43:27.837311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cbe65e05db'
down_revision = 'd3d693b8dd81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_level_name'), 'price_level', ['name'], unique=True)
    op.create_index(op.f('ix_price_level_price'), 'price_level', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_level_price'), table_name='price_level')
    op.drop_index(op.f('ix_price_level_name'), table_name='price_level')
    op.drop_table('price_level')
    # ### end Alembic commands ###
