"""empty message

Revision ID: 587d8fd64a42
Revises: a9d7af936cb5
Create Date: 2019-01-08 15:45:58.171518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587d8fd64a42'
down_revision = 'a9d7af936cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('square', sa.Column('access_token', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('square', 'access_token')
    # ### end Alembic commands ###
