"""empty message

Revision ID: 6ee795a8d431
Revises: 14de905dee13
Create Date: 2018-12-26 20:21:49.914278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee795a8d431'
down_revision = '14de905dee13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mail_opt_out', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_mail_opt_out'), 'user', ['mail_opt_out'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mail_opt_out'), table_name='user')
    op.drop_column('user', 'mail_opt_out')
    # ### end Alembic commands ###
