"""empty message

Revision ID: 981d0f4fdccf
Revises: 6ee795a8d431
Create Date: 2018-12-28 13:33:15.337819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981d0f4fdccf'
down_revision = '6ee795a8d431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_key')
    # ### end Alembic commands ###
