"""empty message

Revision ID: a31adf717e90
Revises: 7f70ea52634f
Create Date: 2019-01-15 20:30:47.710860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31adf717e90'
down_revision = '7f70ea52634f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('renew', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_renew'), 'user', ['renew'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_renew'), table_name='user')
    op.drop_column('user', 'renew')
    # ### end Alembic commands ###
