"""empty message

Revision ID: a908fb8b1d23
Revises: a31adf717e90
Create Date: 2019-01-17 20:24:04.513429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a908fb8b1d23'
down_revision = 'a31adf717e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_renew'), 'user', ['renew'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_renew'), table_name='user')
    # ### end Alembic commands ###
