"""empty message

Revision ID: a908fb8b1d23
Revises: fd06815c1b86
Create Date: 2019-01-17 20:24:04.513429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a908fb8b1d23'
down_revision = 'fd06815c1b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
