"""empty message

Revision ID: a9d7af936cb5
Revises: 33cbe65e05db
Create Date: 2019-01-08 15:37:12.725922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d7af936cb5'
down_revision = '33cbe65e05db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_level_price', table_name='price_level')
    op.create_index(op.f('ix_price_level_price'), 'price_level', ['price'], unique=True)
    op.add_column('user', sa.Column('square_card', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('square_id', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_square_card'), 'user', ['square_card'], unique=False)
    op.create_index(op.f('ix_user_square_id'), 'user', ['square_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_square_id'), table_name='user')
    op.drop_index(op.f('ix_user_square_card'), table_name='user')
    op.drop_column('user', 'square_id')
    op.drop_column('user', 'square_card')
    op.drop_index(op.f('ix_price_level_price'), table_name='price_level')
    op.create_index('ix_price_level_price', 'price_level', ['price'], unique=False)
    # ### end Alembic commands ###
