"""empty message

Revision ID: d3d693b8dd81
Revises: d2028f25feb9
Create Date: 2019-01-07 19:45:49.636979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d693b8dd81'
down_revision = 'd2028f25feb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('square',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=128), nullable=True),
    sa.Column('location_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('square')
    # ### end Alembic commands ###
