"""empty message

Revision ID: fd06815c1b86
Revises: a31adf717e90
Create Date: 2019-01-17 20:09:34.525088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd06815c1b86'
down_revision = 'a31adf717e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('debug', sa.Boolean(), nullable=True))
    op.add_column('email', sa.Column('default_sender', sa.String(length=128), nullable=True))
    op.add_column('email', sa.Column('max_emails', sa.Integer(), nullable=True))
    op.add_column('email', sa.Column('suppress', sa.Boolean(), nullable=True))
    op.add_column('email', sa.Column('use_ssl', sa.Boolean(), nullable=True))
    op.add_column('email', sa.Column('use_tls', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('outgoing_email', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('email', 'use_tls')
    op.drop_column('email', 'use_ssl')
    op.drop_column('email', 'suppress')
    op.drop_column('email', 'max_emails')
    op.drop_column('email', 'default_sender')
    op.drop_column('email', 'debug')
    # ### end Alembic commands ###
